# nixpacks.toml

[phases.setup]
nixPkgs = [
    "php83",
    "php83Packages.composer",
    "php83Extensions.gd",
    "php83Extensions.bcmath",
    "php83Extensions.zip",
    "php83Extensions.pdo_mysql",
    "php83Extensions.fileinfo",
    "php83Extensions.tokenizer",
    "php83Extensions.xml",
    "nodejs_20"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-interaction --no-progress",
    "npm install",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
